
package ltic;

import java.awt.*;
import java.net.URL;
import java.sql.*;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import ltic.ConexionSQL;


public class LticF extends javax.swing.JFrame {
    ConexionSQL coneccion = new ConexionSQL(); 
    
   
    public LticF() {
        initComponents();
    }
    
 

    /**Arreglando Tefa
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        menuf = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        rackf = new javax.swing.JFrame();
        racktb = new javax.swing.JTabbedPane();
        gestionarRackPanel = new javax.swing.JPanel();
        CoRackLab = new javax.swing.JLabel();
        CoRackText = new javax.swing.JTextField();
        CoLaboratorioLab = new javax.swing.JLabel();
        CoLaboCombo = new javax.swing.JComboBox();
        MarcaRackLab = new javax.swing.JLabel();
        MarcaRcakText = new javax.swing.JTextField();
        GuardarRackBoton = new javax.swing.JButton();
        Seguridad = new javax.swing.JPanel();
        SiSeguridadRadio = new javax.swing.JRadioButton();
        NOSeguridadRadio = new javax.swing.JRadioButton();
        EliminarRackBoton = new javax.swing.JButton();
        CancelarRackBoton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        consultaRackPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rackt = new javax.swing.JTable();
        rackbuscartf = new javax.swing.JTextField();
        codigoRackLabel = new javax.swing.JLabel();
        rackbuscarb = new javax.swing.JButton();
        racktodosb = new javax.swing.JButton();
        switchf = new javax.swing.JFrame();
        switchtb = new javax.swing.JTabbedPane();
        gestionarSwitchPanel = new javax.swing.JPanel();
        consultaSwitchPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        switcht = new javax.swing.JTable();
        codigoSwitchLabel = new javax.swing.JLabel();
        buscarswitchtf = new javax.swing.JTextField();
        switchbucarb = new javax.swing.JButton();
        switchtodosb = new javax.swing.JButton();
        puertof = new javax.swing.JFrame();
        puertotb = new javax.swing.JTabbedPane();
        gestionarPuertoPanel = new javax.swing.JPanel();
        switchCombo = new javax.swing.JComboBox();
        switchLabel = new javax.swing.JLabel();
        puertoLabel = new javax.swing.JLabel();
        equipoLabel = new javax.swing.JLabel();
        equipoTextField = new javax.swing.JTextField();
        guardarPuerto = new javax.swing.JButton();
        eliminarPuerto = new javax.swing.JButton();
        puertoTextField = new javax.swing.JTextField();
        consultaPuertoPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        puertot = new javax.swing.JTable();
        codigoPuertoLabel = new javax.swing.JLabel();
        buscarpuertotf = new javax.swing.JTextField();
        puertobuscarb = new javax.swing.JButton();
        puertotodosb = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        switchComboConsulta = new javax.swing.JComboBox();
        gruposeguridad = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        usuariotf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        contrasenatf = new javax.swing.JPasswordField();
        okb = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        menuf.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        menuf.setTitle("Menu");
        menuf.setMinimumSize(new java.awt.Dimension(300, 300));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descarga.png"))); // NOI18N

        jMenu1.setText("Ver");

        jMenu3.setText("Gestionar Racks");

        jMenuItem2.setText("Gestionar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Consulta");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenu1.add(jMenu3);

        jMenu4.setText("Gestionar Switch");

        jMenuItem4.setText("Gestionar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Consulta");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenu1.add(jMenu4);

        jMenu5.setText("Gestionar Puertos");

        jMenuItem6.setText("Gestionar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setText("Consulta");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        menuf.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout menufLayout = new javax.swing.GroupLayout(menuf.getContentPane());
        menuf.getContentPane().setLayout(menufLayout);
        menufLayout.setHorizontalGroup(
            menufLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menufLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        menufLayout.setVerticalGroup(
            menufLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menufLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jMenuItem1.setText("jMenuItem1");

        rackf.setTitle("RACKS");
        rackf.setMinimumSize(new java.awt.Dimension(500, 360));
        rackf.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                rackfComponentShown(evt);
            }
        });

        CoRackLab.setText("Código:");

        CoRackText.setColumns(15);
        CoRackText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CoRackTextFocusLost(evt);
            }
        });

        CoLaboratorioLab.setText("Laboratorio:");

        CoLaboCombo.setMaximumRowCount(15);

        MarcaRackLab.setText("Marca:");

        MarcaRcakText.setColumns(15);

        GuardarRackBoton.setText("Guardar");
        GuardarRackBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarRackBotonActionPerformed(evt);
            }
        });

        gruposeguridad.add(SiSeguridadRadio);
        SiSeguridadRadio.setText("SI");

        gruposeguridad.add(NOSeguridadRadio);
        NOSeguridadRadio.setText("NO");

        javax.swing.GroupLayout SeguridadLayout = new javax.swing.GroupLayout(Seguridad);
        Seguridad.setLayout(SeguridadLayout);
        SeguridadLayout.setHorizontalGroup(
            SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeguridadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SiSeguridadRadio)
                .addGap(18, 18, 18)
                .addComponent(NOSeguridadRadio)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        SeguridadLayout.setVerticalGroup(
            SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeguridadLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiSeguridadRadio)
                    .addComponent(NOSeguridadRadio)))
        );

        EliminarRackBoton.setText("Eliminar");
        EliminarRackBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarRackBotonActionPerformed(evt);
            }
        });

        CancelarRackBoton.setText("Cancelar");
        CancelarRackBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarRackBotonActionPerformed(evt);
            }
        });

        jLabel3.setText("Seguridad:");

        javax.swing.GroupLayout gestionarRackPanelLayout = new javax.swing.GroupLayout(gestionarRackPanel);
        gestionarRackPanel.setLayout(gestionarRackPanelLayout);
        gestionarRackPanelLayout.setHorizontalGroup(
            gestionarRackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestionarRackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gestionarRackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(gestionarRackPanelLayout.createSequentialGroup()
                        .addComponent(CoRackLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CoRackText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CoLaboratorioLab)
                        .addGap(18, 18, 18)
                        .addComponent(CoLaboCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(gestionarRackPanelLayout.createSequentialGroup()
                        .addComponent(MarcaRackLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MarcaRcakText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestionarRackPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Seguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestionarRackPanelLayout.createSequentialGroup()
                        .addComponent(GuardarRackBoton)
                        .addGap(83, 83, 83)
                        .addComponent(EliminarRackBoton)
                        .addGap(61, 61, 61)
                        .addComponent(CancelarRackBoton)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        gestionarRackPanelLayout.setVerticalGroup(
            gestionarRackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestionarRackPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(gestionarRackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoRackLab)
                    .addComponent(CoRackText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CoLaboratorioLab)
                    .addComponent(CoLaboCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(gestionarRackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MarcaRackLab)
                    .addComponent(MarcaRcakText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(gestionarRackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gestionarRackPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addGroup(gestionarRackPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Seguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(gestionarRackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarRackBoton)
                    .addComponent(EliminarRackBoton)
                    .addComponent(CancelarRackBoton))
                .addGap(36, 36, 36))
        );

        racktb.addTab("Gestionar", gestionarRackPanel);

        consultaRackPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                consultaRackPanelComponentShown(evt);
            }
        });

        rackt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Rack", "Codigo Laboratotio", "Marca", "Seguridad"
            }
        ));
        jScrollPane1.setViewportView(rackt);

        codigoRackLabel.setText("Ingrese Código:");

        rackbuscarb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultar.png"))); // NOI18N
        rackbuscarb.setText("Buscar");
        rackbuscarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rackbuscarbActionPerformed(evt);
            }
        });

        racktodosb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vertodas.png"))); // NOI18N
        racktodosb.setText("Ver Todos");
        racktodosb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                racktodosbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaRackPanelLayout = new javax.swing.GroupLayout(consultaRackPanel);
        consultaRackPanel.setLayout(consultaRackPanelLayout);
        consultaRackPanelLayout.setHorizontalGroup(
            consultaRackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaRackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaRackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(consultaRackPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(codigoRackLabel)
                        .addGap(18, 18, 18)
                        .addComponent(rackbuscartf, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(rackbuscarb)
                        .addGap(28, 28, 28)
                        .addComponent(racktodosb)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultaRackPanelLayout.setVerticalGroup(
            consultaRackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaRackPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(consultaRackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rackbuscartf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoRackLabel)
                    .addComponent(rackbuscarb)
                    .addComponent(racktodosb))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        racktb.addTab("Consultar", consultaRackPanel);

        javax.swing.GroupLayout rackfLayout = new javax.swing.GroupLayout(rackf.getContentPane());
        rackf.getContentPane().setLayout(rackfLayout);
        rackfLayout.setHorizontalGroup(
            rackfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rackfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(racktb)
                .addGap(19, 19, 19))
        );
        rackfLayout.setVerticalGroup(
            rackfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rackfLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(racktb)
                .addContainerGap())
        );

        switchf.setTitle("SWITCH");
        switchf.setMinimumSize(new java.awt.Dimension(1000, 374));

        javax.swing.GroupLayout gestionarSwitchPanelLayout = new javax.swing.GroupLayout(gestionarSwitchPanel);
        gestionarSwitchPanel.setLayout(gestionarSwitchPanelLayout);
        gestionarSwitchPanelLayout.setHorizontalGroup(
            gestionarSwitchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        gestionarSwitchPanelLayout.setVerticalGroup(
            gestionarSwitchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        switchtb.addTab("Gestionar", gestionarSwitchPanel);

        consultaSwitchPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                consultaSwitchPanelComponentShown(evt);
            }
        });

        switcht.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Switch", "Código Rack", "Marca Switch", "Fecha Compra", "Tipo", "Precio", "Fibra Optica", "Borde"
            }
        ));
        jScrollPane3.setViewportView(switcht);

        codigoSwitchLabel.setText("Ingrese Código:");

        switchbucarb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultar.png"))); // NOI18N
        switchbucarb.setText("Buscar");
        switchbucarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchbucarbActionPerformed(evt);
            }
        });

        switchtodosb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vertodas.png"))); // NOI18N
        switchtodosb.setText("Ver Todos");
        switchtodosb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchtodosbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaSwitchPanelLayout = new javax.swing.GroupLayout(consultaSwitchPanel);
        consultaSwitchPanel.setLayout(consultaSwitchPanelLayout);
        consultaSwitchPanelLayout.setHorizontalGroup(
            consultaSwitchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaSwitchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(consultaSwitchPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(codigoSwitchLabel)
                .addGap(28, 28, 28)
                .addComponent(buscarswitchtf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(switchbucarb)
                .addGap(120, 120, 120)
                .addComponent(switchtodosb)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        consultaSwitchPanelLayout.setVerticalGroup(
            consultaSwitchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaSwitchPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(consultaSwitchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoSwitchLabel)
                    .addComponent(buscarswitchtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(switchbucarb)
                    .addComponent(switchtodosb))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        switchtb.addTab("Consulta", consultaSwitchPanel);

        javax.swing.GroupLayout switchfLayout = new javax.swing.GroupLayout(switchf.getContentPane());
        switchf.getContentPane().setLayout(switchfLayout);
        switchfLayout.setHorizontalGroup(
            switchfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(switchfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(switchtb)
                .addContainerGap())
        );
        switchfLayout.setVerticalGroup(
            switchfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, switchfLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(switchtb, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );

        puertof.setTitle("Puerto");
        puertof.setMinimumSize(new java.awt.Dimension(600, 500));
        puertof.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                puertofComponentShown(evt);
            }
        });

        switchLabel.setText("Switch:");

        puertoLabel.setText("Puerto:");

        equipoLabel.setText("Equipo");

        equipoTextField.setColumns(10);

        guardarPuerto.setText("Guardar");
        guardarPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPuertoActionPerformed(evt);
            }
        });

        eliminarPuerto.setText("Eliminar");
        eliminarPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPuertoActionPerformed(evt);
            }
        });

        puertoTextField.setColumns(10);
        puertoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                puertoTextFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout gestionarPuertoPanelLayout = new javax.swing.GroupLayout(gestionarPuertoPanel);
        gestionarPuertoPanel.setLayout(gestionarPuertoPanelLayout);
        gestionarPuertoPanelLayout.setHorizontalGroup(
            gestionarPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestionarPuertoPanelLayout.createSequentialGroup()
                .addGroup(gestionarPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gestionarPuertoPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(gestionarPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(equipoLabel)
                            .addComponent(switchLabel))
                        .addGap(18, 18, 18)
                        .addGroup(gestionarPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(switchCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(equipoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(puertoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(puertoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestionarPuertoPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(guardarPuerto)
                        .addGap(43, 43, 43)
                        .addComponent(eliminarPuerto)))
                .addContainerGap(407, Short.MAX_VALUE))
        );
        gestionarPuertoPanelLayout.setVerticalGroup(
            gestionarPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestionarPuertoPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(gestionarPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(switchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(switchLabel)
                    .addComponent(puertoLabel)
                    .addComponent(puertoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(gestionarPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipoLabel)
                    .addComponent(equipoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(gestionarPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarPuerto)
                    .addComponent(eliminarPuerto))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        puertotb.addTab("Gestionar", gestionarPuertoPanel);

        consultaPuertoPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                consultaPuertoPanelComponentShown(evt);
            }
        });

        puertot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Puerto", "Codigo Switch", "Numero Puerto", "Equipo"
            }
        ));
        jScrollPane2.setViewportView(puertot);

        codigoPuertoLabel.setText("Ingrese Numero de Puerto: ");

        puertobuscarb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultar.png"))); // NOI18N
        puertobuscarb.setText("Buscar");
        puertobuscarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertobuscarbActionPerformed(evt);
            }
        });

        puertotodosb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vertodas.png"))); // NOI18N
        puertotodosb.setText("Ver Todos");
        puertotodosb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertotodosbActionPerformed(evt);
            }
        });

        jLabel4.setText("Seleccione Switch:");

        javax.swing.GroupLayout consultaPuertoPanelLayout = new javax.swing.GroupLayout(consultaPuertoPanel);
        consultaPuertoPanel.setLayout(consultaPuertoPanelLayout);
        consultaPuertoPanelLayout.setHorizontalGroup(
            consultaPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaPuertoPanelLayout.createSequentialGroup()
                .addGroup(consultaPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, consultaPuertoPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(consultaPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoPuertoLabel)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(consultaPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(switchComboConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(consultaPuertoPanelLayout.createSequentialGroup()
                                .addComponent(buscarpuertotf, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(puertobuscarb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(puertotodosb))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, consultaPuertoPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        consultaPuertoPanelLayout.setVerticalGroup(
            consultaPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaPuertoPanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(consultaPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaPuertoPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(consultaPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigoPuertoLabel)
                            .addComponent(buscarpuertotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaPuertoPanelLayout.createSequentialGroup()
                        .addGroup(consultaPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(puertobuscarb)
                            .addComponent(puertotodosb))
                        .addGap(1, 1, 1)))
                .addGroup(consultaPuertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(switchComboConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        puertotb.addTab("Consulta", consultaPuertoPanel);

        javax.swing.GroupLayout puertofLayout = new javax.swing.GroupLayout(puertof.getContentPane());
        puertof.getContentPane().setLayout(puertofLayout);
        puertofLayout.setHorizontalGroup(
            puertofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertofLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(puertotb)
                .addContainerGap())
        );
        puertofLayout.setVerticalGroup(
            puertofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertofLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(puertotb)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO");

        jLabel1.setText("Usuario: ");

        jLabel2.setText("Contraseña:");

        okb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check.png"))); // NOI18N
        okb.setText("OK");
        okb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuariotf, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contrasenatf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(okb)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usuariotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(contrasenatf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okb))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbActionPerformed
       String usuario = "Admin";
       String contrasena = "1234";
       
     /* if(usuario==usuariotf.getText() &  contrasena==contrasenatf.getText())
      {
       menuf.setVisible(true);
      }*/
       menuf.setVisible(true);
    }//GEN-LAST:event_okbActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        switchf.setVisible(true);
        switchtb.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        rackf.setVisible(true);
        racktb.setSelectedIndex(0);
        CoRackText.setText("");
        MarcaRcakText.setText("");
        GuardarRackBoton.setEnabled(false);
        EliminarRackBoton.setEnabled(false);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        rackf.setVisible(true);
        racktb.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        switchf.setVisible(true);
        switchtb.setSelectedIndex(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        puertof.setVisible(true);
        puertotb.setSelectedIndex(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        puertof.setVisible(true);
        puertotb.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void switchbucarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchbucarbActionPerformed
        Connection con ;
        con=coneccion.GetConnection();
        ResultSet rs;
        String datos[]= new String [8];
        String codigoSwitch = buscarswitchtf.getText();
        DefaultTableModel pt = (DefaultTableModel) rackt.getModel();
        while (0 < pt.getRowCount()) {
            pt.removeRow(0);
        }
         try
         {
           Statement st = con.createStatement();
           rs = st.executeQuery("select * from switch where CODIGOswitch = '"+codigoSwitch+"'"); 
            while (rs.next())
            {
               datos[0] = rs.getString(1);
               datos[1]= rs.getString(2);
               datos[2]= rs.getString(3);
               datos[3]= ""+ rs.getDate(4);
               datos[4] = ""+ rs.getInt(5);
               datos[5]= ""+ rs.getFloat(6);
               datos[6]= ""+ rs.getFloat(7);
               datos[7]=""+ rs.getInt(8);
               if(datos[6].compareTo(""+1)==0)
                   datos[6]="Si";
               else
                   datos[6]="No";
               if(datos[7].compareTo(""+1)==0)
                   datos[7]="Si";
               else
                   datos[7]="No";
               pt.addRow(datos);
            }
            rs.close();
             con.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
          }   
    }//GEN-LAST:event_switchbucarbActionPerformed

    private void rackfComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_rackfComponentShown
        // TODO add your handling code here:
        CoRackText.setText("");
        MarcaRcakText.setText("");
        GuardarRackBoton.setEnabled(false);
        EliminarRackBoton.setEnabled(false);
         Connection miConexion;
          miConexion=coneccion.GetConnection();
         try
         {
           Statement st = miConexion.createStatement();
            ResultSet rs = st.executeQuery("SELECT CODIGOLAB FROM labortorio"); 
            CoLaboCombo.addItem(" ");
            while (rs.next())
            {
               CoLaboCombo.addItem(rs.getString("CODIGOLAB"));
            }
            rs.close();
             miConexion.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
                }         
    }//GEN-LAST:event_rackfComponentShown

    private void rackbuscarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rackbuscarbActionPerformed
        Connection con ;
        con=coneccion.GetConnection();
        ResultSet rs;
        String datos[]= new String [4];
        String codigoRack = rackbuscartf.getText();
        DefaultTableModel pt = (DefaultTableModel) rackt.getModel();
        while (0 < pt.getRowCount()) {
            pt.removeRow(0);
        }
         try
         {
           Statement st = con.createStatement();
           rs = st.executeQuery("select * from rack where CODIGORACK = '"+codigoRack+"'"); 
            while (rs.next())
            {
               datos[0] = rs.getString("CODIGORACK");
               datos[1]= rs.getString("CODIGOLAB");
               datos[2]= rs.getString("MARCARACK");
               datos[3]=""+ rs.getInt("SEGURIDADRACK");
               if(datos[3].compareTo(""+1)==0)
                   datos[3]="Si";
               else
                   datos[3]="No";
               pt.addRow(datos);
            }
            rs.close();
             con.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
          }   
    }//GEN-LAST:event_rackbuscarbActionPerformed

    private void racktodosbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_racktodosbActionPerformed
         Connection con ;
        con=coneccion.GetConnection();
        ResultSet rs;
        String datos[]= new String [4];
        DefaultTableModel pt = (DefaultTableModel) rackt.getModel();
        while (0 < pt.getRowCount()) {
            pt.removeRow(0);
        }
        try
         {
           Statement st = con.createStatement();
           rs = st.executeQuery("SELECT * FROM rack"); 
            while (rs.next())
            {
               datos[0] = rs.getString("CODIGORACK");
               datos[1]= rs.getString("CODIGOLAB");
               datos[2]= rs.getString("MARCARACK");
               datos[3]=""+ rs.getInt("SEGURIDADRACK");
               if(datos[3].compareTo(""+1)==0)
                   datos[3]="Si";
               else
                   datos[3]="No";
               pt.addRow(datos);
            }
            rs.close();
            con.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
                } 
        
    }//GEN-LAST:event_racktodosbActionPerformed

    private void switchtodosbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchtodosbActionPerformed
        Connection con ;
        con=coneccion.GetConnection();
        ResultSet rs;
        String datos[]= new String [8];
        DefaultTableModel pt = (DefaultTableModel) switcht.getModel();
        while (0 < pt.getRowCount()) {
            pt.removeRow(0);
        }
        try
         {
           Statement st = con.createStatement();
           rs = st.executeQuery("SELECT * FROM switch"); 
            while (rs.next())
            {
               datos[0] = rs.getString(1);
               datos[1]= rs.getString(2);
               datos[2]= rs.getString(3);
               datos[3]= ""+ rs.getDate(4);
               datos[4] = ""+ rs.getInt(5);
               datos[5]= ""+ rs.getFloat(6);
               datos[6]= ""+ rs.getFloat(7);
               datos[7]=""+ rs.getInt(8);
               if(datos[6].compareTo(""+1)==0)
                   datos[6]="Si";
               else
                   datos[6]="No";
               if(datos[7].compareTo(""+1)==0)
                   datos[7]="Si";
               else
                   datos[7]="No";
               pt.addRow(datos);
            }
            rs.close();
            con.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
                } 
    }//GEN-LAST:event_switchtodosbActionPerformed

    private void puertotodosbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertotodosbActionPerformed
        Connection con ;
        con=coneccion.GetConnection();
        ResultSet rs;
        String datos[]= new String [4];
        DefaultTableModel pt = (DefaultTableModel) puertot.getModel();
        while (0 < pt.getRowCount()) {
            pt.removeRow(0);
        }
        try
         {
           Statement st = con.createStatement();
           rs = st.executeQuery("SELECT * FROM puerto"); 
            while (rs.next())
            {
               datos[0] = rs.getString(1);
               datos[1]= rs.getString(2);
               datos[2]= ""+rs.getInt(3);
               datos[3]= rs.getString(4);
              
               pt.addRow(datos);
            }
            rs.close();
            con.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
                } 
    }//GEN-LAST:event_puertotodosbActionPerformed

    private void consultaPuertoPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_consultaPuertoPanelComponentShown
        buscarpuertotf.setText(null);
        DefaultTableModel pt = (DefaultTableModel) puertot.getModel();
        while (0 < pt.getRowCount()) {
            pt.removeRow(0);
        }
         Connection con;
        con=coneccion.GetConnection();
         try
         {
           Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select Codigoswitch from switch"); 
            while (rs.next())
            {
               switchComboConsulta.addItem(rs.getString("Codigoswitch"));
            }
            rs.close();
            con.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
                }
    }//GEN-LAST:event_consultaPuertoPanelComponentShown

    private void consultaSwitchPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_consultaSwitchPanelComponentShown
        buscarswitchtf.setText(null);
        DefaultTableModel pt = (DefaultTableModel) switcht.getModel();
        while (0 < pt.getRowCount()) {
            pt.removeRow(0);
        }
    }//GEN-LAST:event_consultaSwitchPanelComponentShown

    private void consultaRackPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_consultaRackPanelComponentShown
       rackbuscartf.setText(null);
        DefaultTableModel pt = (DefaultTableModel) rackt.getModel();
        while (0 < pt.getRowCount()) {
            pt.removeRow(0);
        }
    }//GEN-LAST:event_consultaRackPanelComponentShown

    private void guardarPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPuertoActionPerformed
        Connection con;
        con=coneccion.GetConnection();
        String codigoSwitch = (String)switchCombo.getSelectedItem();
        String equipoPuerto = equipoTextField.getText();
        int numeroPuerto = Integer.parseInt(puertoTextField.getText());
        String query = "UPDATE PUERTO set EQUIPOPUERTO = '" + equipoPuerto + "' where CODIGOSWITCH = '"+ codigoSwitch +
                "' AND NUMEROPUERTO =" + numeroPuerto; 
         try
         {
            Statement st = con.createStatement();
            int rs = st.executeUpdate(query);
            if(rs == 1)
            {
               switchCombo.setSelectedIndex(-1);
               equipoTextField.setText("");
               puertoTextField.setText("");
            }
            con.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
                }
    }//GEN-LAST:event_guardarPuertoActionPerformed

    private void eliminarPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPuertoActionPerformed
        Connection con;
        con=coneccion.GetConnection();
        String codigoSwitch = (String)switchCombo.getSelectedItem();
        int numeroPuerto = Integer.parseInt(puertoTextField.getText());
        String query = "UPDATE PUERTO set EQUIPOPUERTO = 'Sin Conexion' where CODIGOSWITCH = '"+ codigoSwitch +
                "' AND NUMEROPUERTO =" + numeroPuerto; 
         try
         {
            Statement st = con.createStatement();
            int rs = st.executeUpdate(query);
            if(rs == 1)
            {
               switchCombo.setSelectedIndex(-1);
               equipoTextField.setText("");
               puertoTextField.setText("");
            }
            con.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
                }
    }//GEN-LAST:event_eliminarPuertoActionPerformed

    private void CoRackTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CoRackTextFocusLost
        // TODO add your handling code here:
        GuardarRackBoton.setEnabled(true);
        
        Connection miConexion;
          miConexion=coneccion.GetConnection();
         try
         {
           Statement st = miConexion.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM Rack where CodigoRack='"+CoRackText.getText()+"'"); 
            if (rs.next())
            {
               EliminarRackBoton.setEnabled(true);
               CoRackText.setEnabled(false);
               MarcaRcakText.setText(rs.getString("MARCARACK"));
               CoLaboCombo.setSelectedItem(rs.getString("CODIGOLAB"));
               if(rs.getInt("SEGURIDADRACK")==1)
                    SiSeguridadRadio.setSelected(true);
               else
                   NOSeguridadRadio.setSelected(true);
            }
            
            rs.close();
            miConexion.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
                }



    }//GEN-LAST:event_CoRackTextFocusLost

    private void GuardarRackBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarRackBotonActionPerformed
        Connection miConexion;
        String Codigo=CoRackText.getText();
        String Marca=MarcaRcakText.getText();
        String laboratorio=(String)CoLaboCombo.getSelectedItem();
        Object seguridad;
        if(SiSeguridadRadio.isSelected())
            seguridad=1;
        else
            seguridad=0;
          miConexion=coneccion.GetConnection();
         try
         {
           Statement st = miConexion.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM Rack where CodigoRack='"+CoRackText.getText()+"'"); 
            if (rs.next())
            {
               st.executeUpdate( "UPDATE rack set CODIGOLAB ='"+laboratorio+"', MARCARACK='"+Marca+"', "
                       + "SEGURIDADRACK= "+seguridad+" where CODIGORACK ='"+Codigo+"'");
            }
            else
            {
                st.executeUpdate("INSERT INTO rack (CODIGORACK, CODIGOLAB, MARCARACK, SEGURIDADRACK)"
                + "values('"+Codigo+"', '"+laboratorio+"', '"+Marca+"', "+seguridad+")");
            }
            
            rs.close();
            miConexion.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
                }
         
        CoRackText.setText("");
        MarcaRcakText.setText("");
        CoLaboCombo.setSelectedIndex(0);
        GuardarRackBoton.setEnabled(false);
        EliminarRackBoton.setEnabled(false);
        CoRackText.setEnabled(true);
    }//GEN-LAST:event_GuardarRackBotonActionPerformed

    private void EliminarRackBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarRackBotonActionPerformed
      Connection miConexion;
          miConexion=coneccion.GetConnection();
         try
         {
           Statement st = miConexion.createStatement();
            st.executeUpdate("DELETE from rack where CODIGORACK='"+CoRackText.getText()+"'");
            
            miConexion.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
                }
        CoRackText.setText("");
        MarcaRcakText.setText("");
        CoLaboCombo.setSelectedIndex(0);
        GuardarRackBoton.setEnabled(false);
        EliminarRackBoton.setEnabled(false);
        CoRackText.setEnabled(true);
    }//GEN-LAST:event_EliminarRackBotonActionPerformed

    private void CancelarRackBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarRackBotonActionPerformed
       CoRackText.setText("");
        MarcaRcakText.setText("");
        CoLaboCombo.setSelectedIndex(0);
         GuardarRackBoton.setEnabled(false);
        EliminarRackBoton.setEnabled(false);
        CoRackText.setEnabled(true);
        
    }//GEN-LAST:event_CancelarRackBotonActionPerformed

    private void puertofComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_puertofComponentShown
        Connection con;
        con=coneccion.GetConnection();
         try
         {
           Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select Codigoswitch from switch"); 
            while (rs.next())
            {
               switchCombo.addItem(rs.getString("Codigoswitch"));
            }
            rs.close();
            con.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
                }
    }//GEN-LAST:event_puertofComponentShown

    private void puertoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_puertoTextFieldFocusLost
        Connection con;
        con=coneccion.GetConnection();
        String codigoSwitch = (String)switchCombo.getSelectedItem();
        int numeroPuerto = Integer.parseInt(puertoTextField.getText());
        
        String query = "Select EQUIPOPUERTO from puerto where CODIGOSWITCH = '"+ codigoSwitch +
                "' AND NUMEROPUERTO =" + numeroPuerto ;
         try
         {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query); 
            while (rs.next())
            {
               equipoTextField.setText(rs.getString("EQUIPOPUERTO"));
            }
            rs.close();
            con.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
                }
    }//GEN-LAST:event_puertoTextFieldFocusLost

    private void puertobuscarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertobuscarbActionPerformed
        Connection con ;
        con=coneccion.GetConnection();
        ResultSet rs;
        String datos[]= new String [4];
        String codigoSwitch = (String)switchComboConsulta.getSelectedItem();
        int numeroPuerto = Integer.parseInt(buscarpuertotf.getText());
        DefaultTableModel pt = (DefaultTableModel) puertot.getModel();
        while (0 < pt.getRowCount()) {
            pt.removeRow(0);
        }
        try
         {
           Statement st = con.createStatement();
           if(!codigoSwitch.equals(null))
           rs = st.executeQuery("Select * from puerto where CODIGOSWITCH = '"+ codigoSwitch + "' AND NUMEROPUERTO =" + numeroPuerto ); 
       else
               rs = st.executeQuery("Select * from puerto where NUMEROPUERTO =" + numeroPuerto+""); 
            while (rs.next())
            {
               datos[0] = rs.getString(1);
               datos[1]= rs.getString(2);
               datos[2]= ""+rs.getInt(3);
               datos[3]= rs.getString(4);
              
               pt.addRow(datos);
            }
            rs.close();
            con.close();
          }
                catch( Exception e ){
                System.out.println(e.getMessage());
                e.printStackTrace();
                } 
    }//GEN-LAST:event_puertobuscarbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LticF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LticF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LticF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LticF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LticF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarRackBoton;
    private javax.swing.JComboBox CoLaboCombo;
    private javax.swing.JLabel CoLaboratorioLab;
    private javax.swing.JLabel CoRackLab;
    private javax.swing.JTextField CoRackText;
    private javax.swing.JButton EliminarRackBoton;
    private javax.swing.JButton GuardarRackBoton;
    private javax.swing.JLabel MarcaRackLab;
    private javax.swing.JTextField MarcaRcakText;
    private javax.swing.JRadioButton NOSeguridadRadio;
    private javax.swing.JPanel Seguridad;
    private javax.swing.JRadioButton SiSeguridadRadio;
    private javax.swing.JTextField buscarpuertotf;
    private javax.swing.JTextField buscarswitchtf;
    private javax.swing.JLabel codigoPuertoLabel;
    private javax.swing.JLabel codigoRackLabel;
    private javax.swing.JLabel codigoSwitchLabel;
    private javax.swing.JPanel consultaPuertoPanel;
    private javax.swing.JPanel consultaRackPanel;
    private javax.swing.JPanel consultaSwitchPanel;
    private javax.swing.JPasswordField contrasenatf;
    private javax.swing.JButton eliminarPuerto;
    private javax.swing.JLabel equipoLabel;
    private javax.swing.JTextField equipoTextField;
    private javax.swing.JPanel gestionarPuertoPanel;
    private javax.swing.JPanel gestionarRackPanel;
    private javax.swing.JPanel gestionarSwitchPanel;
    private javax.swing.ButtonGroup gruposeguridad;
    private javax.swing.JButton guardarPuerto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JFrame menuf;
    private javax.swing.JButton okb;
    private javax.swing.JLabel puertoLabel;
    private javax.swing.JTextField puertoTextField;
    private javax.swing.JButton puertobuscarb;
    private javax.swing.JFrame puertof;
    private javax.swing.JTable puertot;
    private javax.swing.JTabbedPane puertotb;
    private javax.swing.JButton puertotodosb;
    private javax.swing.JButton rackbuscarb;
    private javax.swing.JTextField rackbuscartf;
    private javax.swing.JFrame rackf;
    private javax.swing.JTable rackt;
    private javax.swing.JTabbedPane racktb;
    private javax.swing.JButton racktodosb;
    private javax.swing.JComboBox switchCombo;
    private javax.swing.JComboBox switchComboConsulta;
    private javax.swing.JLabel switchLabel;
    private javax.swing.JButton switchbucarb;
    private javax.swing.JFrame switchf;
    private javax.swing.JTable switcht;
    private javax.swing.JTabbedPane switchtb;
    private javax.swing.JButton switchtodosb;
    private javax.swing.JTextField usuariotf;
    // End of variables declaration//GEN-END:variables
}
